//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED1.h
//   Version: 1.40, Updated on 2010/9/19 at 23:40:44                                          
//  Generated by PSoC Designer 5.1.1875.0
//
//  DESCRIPTION: LED1 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED1_INCLUDE
#define LED1_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED1_Stop
#pragma fastcall16  LED1_Start
#pragma fastcall16  LED1_On
#pragma fastcall16  LED1_Off
#pragma fastcall16  LED1_Switch
#pragma fastcall16  LED1_Invert
#pragma fastcall16  LED1_GetState


//-------------------------------------------------
// Constants for LED1 API's.
//-------------------------------------------------
//
#define  LED1_ON   1
#define  LED1_OFF  0

//-------------------------------------------------
// Prototypes of the LED1 API.
//-------------------------------------------------
extern void  LED1_Start(void);                                     
extern void  LED1_Stop(void);                                      
extern void  LED1_On(void);                                      
extern void  LED1_Off(void);                                      
extern void  LED1_Switch(BYTE bSwitch);
extern void  LED1_Invert(void);                                         
extern BYTE  LED1_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
