//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED2.h
//   Version: 1.40, Updated on 2010/9/19 at 23:40:44                                          
//  Generated by PSoC Designer 5.1.1875.0
//
//  DESCRIPTION: LED2 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED2_INCLUDE
#define LED2_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED2_Stop
#pragma fastcall16  LED2_Start
#pragma fastcall16  LED2_On
#pragma fastcall16  LED2_Off
#pragma fastcall16  LED2_Switch
#pragma fastcall16  LED2_Invert
#pragma fastcall16  LED2_GetState


//-------------------------------------------------
// Constants for LED2 API's.
//-------------------------------------------------
//
#define  LED2_ON   1
#define  LED2_OFF  0

//-------------------------------------------------
// Prototypes of the LED2 API.
//-------------------------------------------------
extern void  LED2_Start(void);                                     
extern void  LED2_Stop(void);                                      
extern void  LED2_On(void);                                      
extern void  LED2_Off(void);                                      
extern void  LED2_Switch(BYTE bSwitch);
extern void  LED2_Invert(void);                                         
extern BYTE  LED2_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
