//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED4.h
//   Version: 1.40, Updated on 2010/9/19 at 23:40:44                                          
//  Generated by PSoC Designer 5.1.1875.0
//
//  DESCRIPTION: LED4 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED4_INCLUDE
#define LED4_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED4_Stop
#pragma fastcall16  LED4_Start
#pragma fastcall16  LED4_On
#pragma fastcall16  LED4_Off
#pragma fastcall16  LED4_Switch
#pragma fastcall16  LED4_Invert
#pragma fastcall16  LED4_GetState


//-------------------------------------------------
// Constants for LED4 API's.
//-------------------------------------------------
//
#define  LED4_ON   1
#define  LED4_OFF  0

//-------------------------------------------------
// Prototypes of the LED4 API.
//-------------------------------------------------
extern void  LED4_Start(void);                                     
extern void  LED4_Stop(void);                                      
extern void  LED4_On(void);                                      
extern void  LED4_Off(void);                                      
extern void  LED4_Switch(BYTE bSwitch);
extern void  LED4_Invert(void);                                         
extern BYTE  LED4_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
