//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED6.h
//   Version: 1.40, Updated on 2010/9/19 at 23:40:44                                          
//  Generated by PSoC Designer 5.1.1875.0
//
//  DESCRIPTION: LED6 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2010. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED6_INCLUDE
#define LED6_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED6_Stop
#pragma fastcall16  LED6_Start
#pragma fastcall16  LED6_On
#pragma fastcall16  LED6_Off
#pragma fastcall16  LED6_Switch
#pragma fastcall16  LED6_Invert
#pragma fastcall16  LED6_GetState


//-------------------------------------------------
// Constants for LED6 API's.
//-------------------------------------------------
//
#define  LED6_ON   1
#define  LED6_OFF  0

//-------------------------------------------------
// Prototypes of the LED6 API.
//-------------------------------------------------
extern void  LED6_Start(void);                                     
extern void  LED6_Stop(void);                                      
extern void  LED6_On(void);                                      
extern void  LED6_Off(void);                                      
extern void  LED6_Switch(BYTE bSwitch);
extern void  LED6_Invert(void);                                         
extern BYTE  LED6_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
