/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#include <m8c.h>
// TACH address and mask defines
#pragma	ioport	TACH_Data_ADDR:	0x0
BYTE			TACH_Data_ADDR;
#pragma	ioport	TACH_DriveMode_0_ADDR:	0x100
BYTE			TACH_DriveMode_0_ADDR;
#pragma	ioport	TACH_DriveMode_1_ADDR:	0x101
BYTE			TACH_DriveMode_1_ADDR;
#pragma	ioport	TACH_DriveMode_2_ADDR:	0x3
BYTE			TACH_DriveMode_2_ADDR;
#pragma	ioport	TACH_GlobalSelect_ADDR:	0x2
BYTE			TACH_GlobalSelect_ADDR;
#pragma	ioport	TACH_IntCtrl_0_ADDR:	0x102
BYTE			TACH_IntCtrl_0_ADDR;
#pragma	ioport	TACH_IntCtrl_1_ADDR:	0x103
BYTE			TACH_IntCtrl_1_ADDR;
#pragma	ioport	TACH_IntEn_ADDR:	0x1
BYTE			TACH_IntEn_ADDR;
#define TACH_MASK 0x40
// INS address and mask defines
#pragma	ioport	INS_Data_ADDR:	0x0
BYTE			INS_Data_ADDR;
#pragma	ioport	INS_DriveMode_0_ADDR:	0x100
BYTE			INS_DriveMode_0_ADDR;
#pragma	ioport	INS_DriveMode_1_ADDR:	0x101
BYTE			INS_DriveMode_1_ADDR;
#pragma	ioport	INS_DriveMode_2_ADDR:	0x3
BYTE			INS_DriveMode_2_ADDR;
#pragma	ioport	INS_GlobalSelect_ADDR:	0x2
BYTE			INS_GlobalSelect_ADDR;
#pragma	ioport	INS_IntCtrl_0_ADDR:	0x102
BYTE			INS_IntCtrl_0_ADDR;
#pragma	ioport	INS_IntCtrl_1_ADDR:	0x103
BYTE			INS_IntCtrl_1_ADDR;
#pragma	ioport	INS_IntEn_ADDR:	0x1
BYTE			INS_IntEn_ADDR;
#define INS_MASK 0x80
// DMK address and mask defines
#pragma	ioport	DMK_Data_ADDR:	0x4
BYTE			DMK_Data_ADDR;
#pragma	ioport	DMK_DriveMode_0_ADDR:	0x104
BYTE			DMK_DriveMode_0_ADDR;
#pragma	ioport	DMK_DriveMode_1_ADDR:	0x105
BYTE			DMK_DriveMode_1_ADDR;
#pragma	ioport	DMK_DriveMode_2_ADDR:	0x7
BYTE			DMK_DriveMode_2_ADDR;
#pragma	ioport	DMK_GlobalSelect_ADDR:	0x6
BYTE			DMK_GlobalSelect_ADDR;
#pragma	ioport	DMK_IntCtrl_0_ADDR:	0x106
BYTE			DMK_IntCtrl_0_ADDR;
#pragma	ioport	DMK_IntCtrl_1_ADDR:	0x107
BYTE			DMK_IntCtrl_1_ADDR;
#pragma	ioport	DMK_IntEn_ADDR:	0x5
BYTE			DMK_IntEn_ADDR;
#define DMK_MASK 0x4
// RS485_RE address and mask defines
#pragma	ioport	RS485_RE_Data_ADDR:	0x4
BYTE			RS485_RE_Data_ADDR;
#pragma	ioport	RS485_RE_DriveMode_0_ADDR:	0x104
BYTE			RS485_RE_DriveMode_0_ADDR;
#pragma	ioport	RS485_RE_DriveMode_1_ADDR:	0x105
BYTE			RS485_RE_DriveMode_1_ADDR;
#pragma	ioport	RS485_RE_DriveMode_2_ADDR:	0x7
BYTE			RS485_RE_DriveMode_2_ADDR;
#pragma	ioport	RS485_RE_GlobalSelect_ADDR:	0x6
BYTE			RS485_RE_GlobalSelect_ADDR;
#pragma	ioport	RS485_RE_IntCtrl_0_ADDR:	0x106
BYTE			RS485_RE_IntCtrl_0_ADDR;
#pragma	ioport	RS485_RE_IntCtrl_1_ADDR:	0x107
BYTE			RS485_RE_IntCtrl_1_ADDR;
#pragma	ioport	RS485_RE_IntEn_ADDR:	0x5
BYTE			RS485_RE_IntEn_ADDR;
#define RS485_RE_MASK 0x10
// RX address and mask defines
#pragma	ioport	RX_Data_ADDR:	0x4
BYTE			RX_Data_ADDR;
#pragma	ioport	RX_DriveMode_0_ADDR:	0x104
BYTE			RX_DriveMode_0_ADDR;
#pragma	ioport	RX_DriveMode_1_ADDR:	0x105
BYTE			RX_DriveMode_1_ADDR;
#pragma	ioport	RX_DriveMode_2_ADDR:	0x7
BYTE			RX_DriveMode_2_ADDR;
#pragma	ioport	RX_GlobalSelect_ADDR:	0x6
BYTE			RX_GlobalSelect_ADDR;
#pragma	ioport	RX_IntCtrl_0_ADDR:	0x106
BYTE			RX_IntCtrl_0_ADDR;
#pragma	ioport	RX_IntCtrl_1_ADDR:	0x107
BYTE			RX_IntCtrl_1_ADDR;
#pragma	ioport	RX_IntEn_ADDR:	0x5
BYTE			RX_IntEn_ADDR;
#define RX_MASK 0x20
// TX address and mask defines
#pragma	ioport	TX_Data_ADDR:	0x4
BYTE			TX_Data_ADDR;
#pragma	ioport	TX_DriveMode_0_ADDR:	0x104
BYTE			TX_DriveMode_0_ADDR;
#pragma	ioport	TX_DriveMode_1_ADDR:	0x105
BYTE			TX_DriveMode_1_ADDR;
#pragma	ioport	TX_DriveMode_2_ADDR:	0x7
BYTE			TX_DriveMode_2_ADDR;
#pragma	ioport	TX_GlobalSelect_ADDR:	0x6
BYTE			TX_GlobalSelect_ADDR;
#pragma	ioport	TX_IntCtrl_0_ADDR:	0x106
BYTE			TX_IntCtrl_0_ADDR;
#pragma	ioport	TX_IntCtrl_1_ADDR:	0x107
BYTE			TX_IntCtrl_1_ADDR;
#pragma	ioport	TX_IntEn_ADDR:	0x5
BYTE			TX_IntEn_ADDR;
#define TX_MASK 0x40
// RS485_DE address and mask defines
#pragma	ioport	RS485_DE_Data_ADDR:	0x4
BYTE			RS485_DE_Data_ADDR;
#pragma	ioport	RS485_DE_DriveMode_0_ADDR:	0x104
BYTE			RS485_DE_DriveMode_0_ADDR;
#pragma	ioport	RS485_DE_DriveMode_1_ADDR:	0x105
BYTE			RS485_DE_DriveMode_1_ADDR;
#pragma	ioport	RS485_DE_DriveMode_2_ADDR:	0x7
BYTE			RS485_DE_DriveMode_2_ADDR;
#pragma	ioport	RS485_DE_GlobalSelect_ADDR:	0x6
BYTE			RS485_DE_GlobalSelect_ADDR;
#pragma	ioport	RS485_DE_IntCtrl_0_ADDR:	0x106
BYTE			RS485_DE_IntCtrl_0_ADDR;
#pragma	ioport	RS485_DE_IntCtrl_1_ADDR:	0x107
BYTE			RS485_DE_IntCtrl_1_ADDR;
#pragma	ioport	RS485_DE_IntEn_ADDR:	0x5
BYTE			RS485_DE_IntEn_ADDR;
#define RS485_DE_MASK 0x80
// LED1Pin address and mask defines
#pragma	ioport	LED1Pin_Data_ADDR:	0x8
BYTE			LED1Pin_Data_ADDR;
#pragma	ioport	LED1Pin_DriveMode_0_ADDR:	0x108
BYTE			LED1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED1Pin_DriveMode_1_ADDR:	0x109
BYTE			LED1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED1Pin_DriveMode_2_ADDR:	0xb
BYTE			LED1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED1Pin_GlobalSelect_ADDR:	0xa
BYTE			LED1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED1Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED1Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED1Pin_IntEn_ADDR:	0x9
BYTE			LED1Pin_IntEn_ADDR;
#define LED1Pin_MASK 0x1
// LED1Pin Shadow defines
//   LED1Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED1Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED2Pin address and mask defines
#pragma	ioport	LED2Pin_Data_ADDR:	0x8
BYTE			LED2Pin_Data_ADDR;
#pragma	ioport	LED2Pin_DriveMode_0_ADDR:	0x108
BYTE			LED2Pin_DriveMode_0_ADDR;
#pragma	ioport	LED2Pin_DriveMode_1_ADDR:	0x109
BYTE			LED2Pin_DriveMode_1_ADDR;
#pragma	ioport	LED2Pin_DriveMode_2_ADDR:	0xb
BYTE			LED2Pin_DriveMode_2_ADDR;
#pragma	ioport	LED2Pin_GlobalSelect_ADDR:	0xa
BYTE			LED2Pin_GlobalSelect_ADDR;
#pragma	ioport	LED2Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED2Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED2Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED2Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED2Pin_IntEn_ADDR:	0x9
BYTE			LED2Pin_IntEn_ADDR;
#define LED2Pin_MASK 0x2
// LED2Pin Shadow defines
//   LED2Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED2Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED3Pin address and mask defines
#pragma	ioport	LED3Pin_Data_ADDR:	0x8
BYTE			LED3Pin_Data_ADDR;
#pragma	ioport	LED3Pin_DriveMode_0_ADDR:	0x108
BYTE			LED3Pin_DriveMode_0_ADDR;
#pragma	ioport	LED3Pin_DriveMode_1_ADDR:	0x109
BYTE			LED3Pin_DriveMode_1_ADDR;
#pragma	ioport	LED3Pin_DriveMode_2_ADDR:	0xb
BYTE			LED3Pin_DriveMode_2_ADDR;
#pragma	ioport	LED3Pin_GlobalSelect_ADDR:	0xa
BYTE			LED3Pin_GlobalSelect_ADDR;
#pragma	ioport	LED3Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED3Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED3Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED3Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED3Pin_IntEn_ADDR:	0x9
BYTE			LED3Pin_IntEn_ADDR;
#define LED3Pin_MASK 0x4
// LED3Pin Shadow defines
//   LED3Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED3Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED4Pin address and mask defines
#pragma	ioport	LED4Pin_Data_ADDR:	0x8
BYTE			LED4Pin_Data_ADDR;
#pragma	ioport	LED4Pin_DriveMode_0_ADDR:	0x108
BYTE			LED4Pin_DriveMode_0_ADDR;
#pragma	ioport	LED4Pin_DriveMode_1_ADDR:	0x109
BYTE			LED4Pin_DriveMode_1_ADDR;
#pragma	ioport	LED4Pin_DriveMode_2_ADDR:	0xb
BYTE			LED4Pin_DriveMode_2_ADDR;
#pragma	ioport	LED4Pin_GlobalSelect_ADDR:	0xa
BYTE			LED4Pin_GlobalSelect_ADDR;
#pragma	ioport	LED4Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED4Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED4Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED4Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED4Pin_IntEn_ADDR:	0x9
BYTE			LED4Pin_IntEn_ADDR;
#define LED4Pin_MASK 0x8
// LED4Pin Shadow defines
//   LED4Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED4Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED5Pin address and mask defines
#pragma	ioport	LED5Pin_Data_ADDR:	0x8
BYTE			LED5Pin_Data_ADDR;
#pragma	ioport	LED5Pin_DriveMode_0_ADDR:	0x108
BYTE			LED5Pin_DriveMode_0_ADDR;
#pragma	ioport	LED5Pin_DriveMode_1_ADDR:	0x109
BYTE			LED5Pin_DriveMode_1_ADDR;
#pragma	ioport	LED5Pin_DriveMode_2_ADDR:	0xb
BYTE			LED5Pin_DriveMode_2_ADDR;
#pragma	ioport	LED5Pin_GlobalSelect_ADDR:	0xa
BYTE			LED5Pin_GlobalSelect_ADDR;
#pragma	ioport	LED5Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED5Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED5Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED5Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED5Pin_IntEn_ADDR:	0x9
BYTE			LED5Pin_IntEn_ADDR;
#define LED5Pin_MASK 0x10
// LED5Pin Shadow defines
//   LED5Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED5Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED6Pin address and mask defines
#pragma	ioport	LED6Pin_Data_ADDR:	0x8
BYTE			LED6Pin_Data_ADDR;
#pragma	ioport	LED6Pin_DriveMode_0_ADDR:	0x108
BYTE			LED6Pin_DriveMode_0_ADDR;
#pragma	ioport	LED6Pin_DriveMode_1_ADDR:	0x109
BYTE			LED6Pin_DriveMode_1_ADDR;
#pragma	ioport	LED6Pin_DriveMode_2_ADDR:	0xb
BYTE			LED6Pin_DriveMode_2_ADDR;
#pragma	ioport	LED6Pin_GlobalSelect_ADDR:	0xa
BYTE			LED6Pin_GlobalSelect_ADDR;
#pragma	ioport	LED6Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED6Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED6Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED6Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED6Pin_IntEn_ADDR:	0x9
BYTE			LED6Pin_IntEn_ADDR;
#define LED6Pin_MASK 0x20
// LED6Pin Shadow defines
//   LED6Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED6Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// INCL_DN address and mask defines
#pragma	ioport	INCL_DN_Data_ADDR:	0x8
BYTE			INCL_DN_Data_ADDR;
#pragma	ioport	INCL_DN_DriveMode_0_ADDR:	0x108
BYTE			INCL_DN_DriveMode_0_ADDR;
#pragma	ioport	INCL_DN_DriveMode_1_ADDR:	0x109
BYTE			INCL_DN_DriveMode_1_ADDR;
#pragma	ioport	INCL_DN_DriveMode_2_ADDR:	0xb
BYTE			INCL_DN_DriveMode_2_ADDR;
#pragma	ioport	INCL_DN_GlobalSelect_ADDR:	0xa
BYTE			INCL_DN_GlobalSelect_ADDR;
#pragma	ioport	INCL_DN_IntCtrl_0_ADDR:	0x10a
BYTE			INCL_DN_IntCtrl_0_ADDR;
#pragma	ioport	INCL_DN_IntCtrl_1_ADDR:	0x10b
BYTE			INCL_DN_IntCtrl_1_ADDR;
#pragma	ioport	INCL_DN_IntEn_ADDR:	0x9
BYTE			INCL_DN_IntEn_ADDR;
#define INCL_DN_MASK 0x40
// INCL_DN Shadow defines
//   INCL_DN_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define INCL_DN_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// INCL_UP address and mask defines
#pragma	ioport	INCL_UP_Data_ADDR:	0x8
BYTE			INCL_UP_Data_ADDR;
#pragma	ioport	INCL_UP_DriveMode_0_ADDR:	0x108
BYTE			INCL_UP_DriveMode_0_ADDR;
#pragma	ioport	INCL_UP_DriveMode_1_ADDR:	0x109
BYTE			INCL_UP_DriveMode_1_ADDR;
#pragma	ioport	INCL_UP_DriveMode_2_ADDR:	0xb
BYTE			INCL_UP_DriveMode_2_ADDR;
#pragma	ioport	INCL_UP_GlobalSelect_ADDR:	0xa
BYTE			INCL_UP_GlobalSelect_ADDR;
#pragma	ioport	INCL_UP_IntCtrl_0_ADDR:	0x10a
BYTE			INCL_UP_IntCtrl_0_ADDR;
#pragma	ioport	INCL_UP_IntCtrl_1_ADDR:	0x10b
BYTE			INCL_UP_IntCtrl_1_ADDR;
#pragma	ioport	INCL_UP_IntEn_ADDR:	0x9
BYTE			INCL_UP_IntEn_ADDR;
#define INCL_UP_MASK 0x80
// INCL_UP Shadow defines
//   INCL_UP_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define INCL_UP_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
