/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "E2PROM.h"
#include "LED1.h"
#include "LED2.h"
#include "LED3.h"
#include "LED4.h"
#include "LED5.h"
#include "LED6.h"
#include "Timer8.h"
#include "UART.h"

#endif
